// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4pGn2qzWQYneg5tRT74HmWUBFjiDV3fk',
    appId: '1:617369470412:web:285e15a03e8e64069b8969',
    messagingSenderId: '617369470412',
    projectId: 'women-safety-1-a45e7',
    authDomain: 'women-safety-1-a45e7.firebaseapp.com',
    storageBucket: 'women-safety-1-a45e7.appspot.com',
    measurementId: 'G-KPXWHF24B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsRW5veDqrSG7WS34voN3Q6EIVA48BELw',
    appId: '1:617369470412:android:487bf217cd839f249b8969',
    messagingSenderId: '617369470412',
    projectId: 'women-safety-1-a45e7',
    storageBucket: 'women-safety-1-a45e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCceofpuZDeEVoGsCLUQ7IG7bby0mlzGaI',
    appId: '1:617369470412:ios:20ffa13e3d3924f59b8969',
    messagingSenderId: '617369470412',
    projectId: 'women-safety-1-a45e7',
    storageBucket: 'women-safety-1-a45e7.appspot.com',
    iosClientId: '617369470412-0vp2nvp9879l1kua5c3g4qi9cmbmbjei.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafety1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCceofpuZDeEVoGsCLUQ7IG7bby0mlzGaI',
    appId: '1:617369470412:ios:20ffa13e3d3924f59b8969',
    messagingSenderId: '617369470412',
    projectId: 'women-safety-1-a45e7',
    storageBucket: 'women-safety-1-a45e7.appspot.com',
    iosClientId: '617369470412-0vp2nvp9879l1kua5c3g4qi9cmbmbjei.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafety1',
  );
}
